### ISSUE TITLE
High-quality sources for music

### ISSUE THREAD

**Issue by Calinou** [redeclipse/sounds#4]
Out of curiosity, are there any higher-quality/lossless sources for the [music](https://github.com/redeclipse/sounds/tree/master/music) available? I'm not sure if JoJo is still reachable today.

This way, we could re-encode the soundtrack included in the game with higher quality and possibly release a standalone soundtrack package (as is popular in indie games today).

**Comment by acerspyro** [comment]
Hijacking this thread, I'd also like to get in touch with the person who developed the player model to get the source texture files so we can redo the player model. I think it's LuckyStrikeRx, but I heard it was contracted.

**Comment by graphitemaster** [comment]
It was fleeky

**Comment by qreeves** [comment]
Jojo doesn't have any of the files for the original music, I've already asked about it. I'm thinking about commissioning a new soundtrack.
